// packages/react/src/Renderer.tsx
import { createElement, Fragment } from 'react';
import type { ReactNode, ComponentType } from 'react';
import type { SerializedTag, RendererNode } from '@refrakt-md/types';
import { isTag, extractComponentInterface, renderToHtml } from '@refrakt-md/transform';

export interface RendererProps {
	node: RendererNode;
	/** typeof name → React component (component overrides) */
	components?: Record<string, ComponentType<any>>;
	/** HTML element name → React component (element-level overrides) */
	elements?: Record<string, ComponentType<any>>;
}

const VOID_ELEMENTS = new Set([
	'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
	'link', 'meta', 'param', 'source', 'track', 'wbr',
]);

/**
 * Convert serialized tag attributes to React-compatible props.
 * - Renames `class` → `className`
 * - Strips internal `$$mdtype` attribute
 * - Drops null/undefined/false values
 * - Converts `true` to empty string (bare HTML attribute)
 */
function toReactProps(attrs: Record<string, any>): Record<string, any> {
	const result: Record<string, any> = {};
	for (const [k, v] of Object.entries(attrs)) {
		if (k === '$$mdtype' || v === undefined || v === null || v === false) continue;
		if (k === 'class') { result.className = v; continue; }
		result[k] = v === true ? '' : v;
	}
	return result;
}

/**
 * Render a RendererNode tree as a ReactNode.
 *
 * This is the primary rendering function for the React renderer (ADR-008).
 *
 * When a tag has a `data-rune` attribute matching a registered component:
 * 1. `extractComponentInterface` partitions children into properties, named refs, and content
 * 2. Properties become named React props (scalar strings)
 * 3. Named refs become ReactNode props (pre-rendered HTML via dangerouslySetInnerHTML)
 * 4. Anonymous content becomes the `children` prop
 * 5. The original `tag` is passed for backwards-compatible escape-hatch access
 *
 * Element overrides (table, pre) receive `tag` and `children` props.
 *
 * Props are passed through explicitly (no React Context) so the renderer
 * works in both Server Components and Client Components.
 */
export function Renderer({ node, components, elements }: RendererProps): ReactNode {
	if (node === null || node === undefined) return null;
	if (typeof node === 'string') return node;
	if (typeof node === 'number') return String(node);

	if (Array.isArray(node)) {
		return createElement(Fragment, null,
			...node.map((child, i) =>
				createElement(Renderer, { key: i, node: child, components, elements }),
			),
		);
	}

	if (!isTag(node)) return null;

	// Component override dispatch via data-rune attribute
	const runeType = node.attributes?.['data-rune'];
	const Component = runeType && components?.[runeType];

	if (Component) {
		const iface = extractComponentInterface(node);

		// Convert named refs to ReactNode values (pre-rendered HTML)
		const refNodes: Record<string, ReactNode> = {};
		for (const [name, tags] of Object.entries(iface.refs)) {
			const html = tags.map(t => renderToHtml(t)).join('');
			refNodes[name] = createElement('div', {
				'data-ref': name,
				dangerouslySetInnerHTML: { __html: html },
			});
		}

		// Convert anonymous children to ReactNode
		const childContent = iface.children.length > 0
			? createElement(Fragment, null,
				...iface.children.map((child, i) =>
					createElement(Renderer, { key: i, node: child, components, elements }),
				),
			)
			: undefined;

		return createElement(Component, {
			...iface.properties,
			...refNodes,
			children: childContent,
			tag: node,
		});
	}

	// Element override dispatch via tag name
	const ElementOverride = elements?.[node.name];

	if (ElementOverride) {
		return createElement(ElementOverride, { tag: node },
			...node.children.map((child, i) =>
				createElement(Renderer, { key: i, node: child, components, elements }),
			),
		);
	}

	// SVG — render as raw HTML to avoid namespace issues
	if (node.name === 'svg') {
		return createElement('span', {
			dangerouslySetInnerHTML: { __html: renderToHtml(node) },
		});
	}

	// Null-named tags (Markdoc document root) — render children without wrapper
	if (!node.name) {
		return createElement(Fragment, null,
			...node.children.map((child, i) =>
				createElement(Renderer, { key: i, node: child, components, elements }),
			),
		);
	}

	// Void elements
	if (VOID_ELEMENTS.has(node.name)) {
		return createElement(node.name, toReactProps(node.attributes));
	}

	// Raw HTML content (code blocks, raw-html attribute)
	const isRaw = node.attributes?.['data-codeblock'] || node.attributes?.['data-raw-html'];
	if (isRaw) {
		const html = node.children.map(child => {
			if (typeof child === 'string') return child;
			return renderToHtml(child);
		}).join('');
		return createElement(node.name, {
			...toReactProps(node.attributes),
			dangerouslySetInnerHTML: { __html: html },
		});
	}

	// Regular HTML element — recursively render children
	return createElement(node.name, toReactProps(node.attributes),
		...node.children.map((child, i) =>
			createElement(Renderer, { key: i, node: child, components, elements }),
		),
	);
}

// packages/svelte/src/Renderer.svelte
<script lang="ts" module>
	export type { SerializedTag, RendererNode } from './types.js';
</script>

<script lang="ts">
	import { createRawSnippet } from 'svelte';
	import type { Snippet } from 'svelte';
	import type { Component } from 'svelte';
	import type { SerializedTag, RendererNode } from './types.js';
	import { getComponent, getElementOverrides } from './context.js';
	import { extractComponentInterface } from '@refrakt-md/transform';
	import Renderer from './Renderer.svelte';

	let { node, overrides }: { node: RendererNode; overrides?: Record<string, Component<any>> } = $props();

	function isTag(n: unknown): n is SerializedTag {
		return n !== null && typeof n === 'object' && (n as any).$$mdtype === 'Tag';
	}

	/** Filter out attributes that shouldn't be rendered as HTML attributes */
	function htmlAttrs(attrs: Record<string, any>): Record<string, any> {
		const result: Record<string, any> = {};
		for (const [k, v] of Object.entries(attrs)) {
			if (v === undefined || v === null || v === false) continue;
			result[k] = v === true ? '' : String(v);
		}
		return result;
	}

	function escapeAttr(str: string): string {
		return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
	}

	/** Serialize an SVG tag tree to HTML string. Using {@html} avoids SVG namespace
	 *  issues that occur when <svelte:element> creates child SVG elements (path, circle, etc.)
	 *  outside the SVG namespace context during client-side navigation. */
	function svgToHtml(tag: SerializedTag): string {
		const attrs = Object.entries(htmlAttrs(tag.attributes))
			.map(([k, v]) => ` ${k}="${escapeAttr(v)}"`)
			.join('');
		const children = tag.children.map(child => {
			if (typeof child === 'string') return escapeAttr(child);
			if (isTag(child)) return svgToHtml(child);
			return '';
		}).join('');
		return `<${tag.name}${attrs}>${children}</${tag.name}>`;
	}

	const VOID_ELEMENTS = new Set([
		'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
		'link', 'meta', 'param', 'source', 'track', 'wbr',
	]);

	/** Render a RendererNode tree to an HTML string, handling codeblock/raw-html content */
	function nodeToHtml(n: RendererNode): string {
		if (n === null || n === undefined) return '';
		if (typeof n === 'string') return escapeAttr(n);
		if (typeof n === 'number') return String(n);
		if (Array.isArray(n)) return n.map(nodeToHtml).join('');
		if (!isTag(n)) return '';
		if (n.name === 'svg') return svgToHtml(n);

		const attrs = Object.entries(htmlAttrs(n.attributes))
			.map(([k, v]) => ` ${k}="${escapeAttr(v)}"`)
			.join('');

		if (VOID_ELEMENTS.has(n.name)) return `<${n.name}${attrs}>`;

		const isRaw = n.attributes?.['data-codeblock'] || n.attributes?.['data-raw-html'];
		const inner = n.children.map(child => {
			if (isRaw && typeof child === 'string') return child;
			return nodeToHtml(child);
		}).join('');

		return `<${n.name}${attrs}>${inner}</${n.name}>`;
	}

	/** Create a Svelte 5 snippet from an array of serialized nodes */
	function createNodeSnippet(nodes: RendererNode[]): Snippet {
		return createRawSnippet(() => ({
			render: () => {
				if (nodes.length === 1 && isTag(nodes[0])) {
					return nodeToHtml(nodes[0]);
				}
				return `<div data-snippet-wrapper>${nodes.map(nodeToHtml).join('')}</div>`;
			},
		}));
	}

	const globalOverrides = getElementOverrides();
	const merged = $derived(overrides
		? { ...globalOverrides, ...overrides }
		: globalOverrides);
</script>

{#if Array.isArray(node)}
	{#each node as child}
		<Renderer node={child} overrides={merged} />
	{/each}
{:else if node === null || node === undefined}
	<!-- empty -->
{:else if typeof node === 'string'}
	{node}
{:else if typeof node === 'number'}
	{String(node)}
{:else if isTag(node)}
	{@const Component = node.attributes?.['data-rune'] ? getComponent(node.attributes['data-rune']) : undefined}
	{@const ElementOverride = !Component && merged?.[node.name] ? merged[node.name] : undefined}
	{#if Component}
		{@const iface = extractComponentInterface(node)}
		{@const refSnippets = Object.fromEntries(
			Object.entries(iface.refs).map(([name, tags]) => [name, createNodeSnippet(tags)])
		)}
		{@const childSnippet = iface.children.length > 0 ? createNodeSnippet(iface.children) : undefined}
		<Component {...iface.properties} {...refSnippets} children={childSnippet} tag={node} />
	{:else if ElementOverride}
		<ElementOverride tag={node}>
			{#each node.children as child}
				<Renderer node={child} overrides={merged} />
			{/each}
		</ElementOverride>
	{:else if node.name === 'svg'}
		{@html svgToHtml(node)}
	{:else}
		<svelte:element this={node.name} {...htmlAttrs(node.attributes)}>
			{#each node.children as child}
				{#if (node.attributes?.['data-codeblock'] || node.attributes?.['data-raw-html']) && typeof child === 'string'}
					{@html child}
				{:else}
					<Renderer node={child} overrides={merged} />
				{/if}
			{/each}
		</svelte:element>
	{/if}
{/if}
